### ISSUE TITLE
Пропал доступ к mi облаку

### ISSUE THREAD

**Issue by semikor** [BOOMER74/node-red-contrib-mihome#5]
Приветствую, Сергей!
Позволь поблагодарить, за проделанную работу!!!
С неделю назад пропал доступ - все ноды (и devices и th monitor) горят красным (offline).
Пропал сам по себе - ничего особенного не делал., проработало с полгода..
Аккаунт проверил (Country = ru) - на смарте доступ и данные есть, в узле cloud вбивал все еще раз.
Подаю true на вход - на выходе пусто.
Спасибо!
NR v2.1.4 на Pi4
* Package version: 1.1.1
* Node name: mihome-cloud

**Describe the bug**

A description of what the bug is.

**To Reproduce**

Steps/conditions to reproduce:

1. Describe input
2. What's settings
3. Received output

**Expected behavior**

A description of what you expected to happen.

**Additional context**

**Comment by semikor** [comment]
Заметил при запуске NR:
(node:22697) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isLoggedIn' of null
    at checkConnection (/home/pi/.node-red/node_modules/node-red-contrib-mihome/nodes/mihome-cloud.js:56:29)
    at /home/pi/.node-red/node_modules/node-red-contrib-mihome/nodes/mihome-cloud.js:63:11
    at new Promise (<anonymous>)
    at Cloud.init (/home/pi/.node-red/node_modules/node-red-contrib-mihome/nodes/mihome-cloud.js:54:15)
    at new Devices (/home/pi/.node-red/node_modules/node-red-contrib-mihome/nodes/mihome-devices.js:17:13)
    at Object.createNode (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/util.js:87:27)
    at Flow.start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:206:48)
    at start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/index.js:371:33)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22697) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:22697) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by semikor** [comment]
Прошу прощения за беспокойство!
Заработало.
